version: "3.9"

services:
  backend:
    build:
      context: ./backend-deploy
    container_name: backend-deploy
    ports:
      - "5000:5000"
    env_file:
      - ./.env # contains your MONGODB_URI for Atlas
    volumes:
      - ./backend-deploy/uploads:/app/uploads # persist uploaded images
    depends_on: []

  frontend:
    build:
      context: ./frontend-deploy
      args:
        VITE_API_BASE_URL: http://backend:5000/api
    container_name: frontend-deploy
    ports:
      - "5173:3000"
    depends_on:
      - backend
